fix: Add user to AuthFactor serializer
ocadotechnology/codeforlife-portal-backend pull request #375
Opened 2024-12-30 14:40 UTC by faucomte97

2025-01-17 11:18 UTC, SKairinos requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375)* status: all files reviewed, 8 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/auth/token_generators.py` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnrCTa9lzYCpcOWYE2:-OGnrCTbEHfKRY4zqEuL:bpdt2d5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/auth/token_generators.py#L31)):*
> ```Python
>         return f"user:{pk}"
> 
>     def make_token(self, user_or_pk: t.Union[User, t.Any], new_email: str = ""):
> ```

`email: str`

This should always be required, not just for new emails.



_Code quote:_
```Python
new_email: str = ""
```
___
*[`src/api/auth/token_generators.py` line 84 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnp_zF7CThiERTtalA:-OGnp_zF7CThiERTtalB:b-y6tytj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/auth/token_generators.py#L84)):*
> ```Python
>         return True
> 
>     def get_new_email(self, user_or_pk: t.Union[User, t.Any], token: str):
> ```

I would get rid of this helper. In check_token, instead of returning False, return None. Instead of returning True, return the decoded JWT.
___
*[`src/api/views/user.py` line 193 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnyF0E1qJ5KC8KzRYd:-OGnyF0E1qJ5KC8KzRYe:b-55vvba) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/views/user.py#L193)):*
> ```Python
>             user.email = new_email
>             user.username = new_email
>             user.save()
> ```

transfer this logic to the serializer's update method. Also, in the serializer, return `token` instead of `value`. Then do validated_data["token"]["email"] in `update`.



_Code quote:_
```Python
        new_email = email_verification_token_generator.get_new_email(
            user, url_params["token"]
        )
        if new_email != "":
            user.email = new_email
            user.username = new_email
            user.save()
```
___
*[`src/api/signals/user.py` line 104 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnx3y9381Yynmb2odR:-OGnx3y9381Yynmb2odS:b-c7nz0b) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/signals/user.py#L104)):*
> ```Python
> 
>     # TODO: Send a email address update confirmation email (new template
>     # required) to old email address after successful email update
> ```

we had this code - put it back please
___
*[`src/api/views/user_test.py` line 420 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnz6qT0Me4JKIieGm1:-OGnz6qT0Me4JKIieGm2:bf4lf4o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/views/user_test.py#L420)):*
> ```Python
>         assert user.userprofile.is_verified
> 
>     def test_verify_new_email_address(self):
> ```

delete this test and merge with one above.
___
*[`src/api/serializers/user.py` line 285 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnqBeo87hQ8gD8nxel:-OGnqBeo87hQ8gD8nxem:bz8c8me) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/serializers/user.py#L285)):*
> ```Python
>                 #  notify them of join request.
> 
>         new_email = validated_data.pop("email", None)
> ```

`email = validated_data.pop("email", None)`

keep the variable names consistent to avoid confusion. the old email is `instance.email`



_Code quote:_
```Python
new_email = validated_data.pop("email", None)
```
___
*[`src/api/serializers/user.py` line 286 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnqTjC7kK1gbCmFti9:-OGnqTjDE12ER-e8fQJ3:bkd3jj4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/serializers/user.py#L286)):*
> ```Python
> 
>         new_email = validated_data.pop("email", None)
>         if new_email is not None and new_email != instance.email:
> ```

general rule: email addresses are case insensitive.



_Code quote:_
```Python
new_email != instance.email
```
___
*[`src/api/signals/user_test.py` line 66 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnxXQx8N_KWxAfg7_K:-OGnxXQx8N_KWxAfg7_L:b2x6v44) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/aa37bbc35bc4916184296b544574b0280200bcca/src/api/signals/user_test.py#L66)):*
> ```Python
>             send_mail.assert_has_calls(
>                 [
>                     call(
> ```

put this back. just don't check the second call


<!-- Sent from Reviewable.io -->

2025-01-17 13:55 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375)* status: 2 of 11 files reviewed, 8 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`src/api/auth/token_generators.py` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnrCTa9lzYCpcOWYE2:-OGoPM4tD1TeZj8dLtob:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/auth/token_generators.py#L31)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

`email: str`

This should always be required, not just for new emails.
</blockquote></details>

Done.
___
*[`src/api/auth/token_generators.py` line 84 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnp_zF7CThiERTtalA:-OGoIiwu1oI3rgnfIQia:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/auth/token_generators.py#L84)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

I would get rid of this helper. In check_token, instead of returning False, return None. Instead of returning True, return the decoded JWT.
</blockquote></details>

Done.
___
*[`src/api/serializers/user.py` line 285 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnqBeo87hQ8gD8nxel:-OGoJCl44kR5mdl6zDXo:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/serializers/user.py#L285)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

`email = validated_data.pop("email", None)`

keep the variable names consistent to avoid confusion. the old email is `instance.email`
</blockquote></details>

Done.
___
*[`src/api/serializers/user.py` line 286 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnqTjC7kK1gbCmFti9:-OGoJTQz1IuK0t2MiE0A:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/serializers/user.py#L286)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

general rule: email addresses are case insensitive.
</blockquote></details>

Done.
___
*[`src/api/signals/user.py` line 104 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnx3y9381Yynmb2odR:-OGoKHvA9wdGcoJHSFFP:b4vwtn2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/signals/user.py#L104)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

we had this code - put it back please
</blockquote></details>

I'm confused - we didn't, this is the new feature we discussed earlier this week where we need a new template in DD to notify the old email address that the email update was done successfully.

The code was already in here, I've moved to the serializer as it deals with the earlier emails in the flow.
___
*[`src/api/signals/user_test.py` line 66 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnxXQx8N_KWxAfg7_K:-OGoKa7t0ee1BiVQdHrp:b4108s) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/aa37bbc35bc4916184296b544574b0280200bcca/src/api/signals/user_test.py#L66)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

put this back. just don't check the second call
</blockquote></details>

I don't understand, both templates are sent at the same time when the serializer's `update` function gets called.
On post save now, nothing else happens.
___
*[`src/api/views/user.py` line 193 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnyF0E1qJ5KC8KzRYd:-OGoMyKp3nNZuViTIvPR:b-2g62jq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/views/user.py#L193)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

transfer this logic to the serializer's update method. Also, in the serializer, return `token` instead of `value`. Then do validated_data["token"]["email"] in `update`.
</blockquote></details>

I tried doing that, but I'm getting a `KeyError` on `validated_data`. Not sure what I'm doing wrong?
___
*[`src/api/views/user_test.py` line 420 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnz6qT0Me4JKIieGm1:-OGoR4m_BznNgf8Ik8-U:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/views/user_test.py#L420)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

delete this test and merge with one above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-17 17:36 UTC, SKairinos requested changes
> Reviewed 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/signals/user.py` line 104 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnx3y9381Yynmb2odR:-OGpKMw6Br_jAXIQgUQ3:b2e6yj8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/signals/user.py#L104)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I'm confused - we didn't, this is the new feature we discussed earlier this week where we need a new template in DD to notify the old email address that the email update was done successfully.

The code was already in here, I've moved to the serializer as it deals with the earlier emails in the flow.
</blockquote></details>

let's discuss on quick call
___
*[`src/api/signals/user_test.py` line 66 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnxXQx8N_KWxAfg7_K:-OGpKbF09rC-Uwgpb4BO:b2e6yj8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/aa37bbc35bc4916184296b544574b0280200bcca/src/api/signals/user_test.py#L66)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I don't understand, both templates are sent at the same time when the serializer's `update` function gets called.
On post save now, nothing else happens.
</blockquote></details>

let's discuss on quick call
___
*[`src/api/views/user.py` line 193 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnyF0E1qJ5KC8KzRYd:-OGpILJaAHQncnb4nRQ9:b2e6yj8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/views/user.py#L193)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I tried doing that, but I'm getting a `KeyError` on `validated_data`. Not sure what I'm doing wrong?
</blockquote></details>

let's discuss on quick call
___
*[`src/api/views/user_test.py` line 406 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGpIaXe0krdUmtHeL5F:-OGpIaXe0krdUmtHeL5G:b-qq5rlq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/885dd92bb4c3575d654fe93c1bdcab0fa691fa46/src/api/views/user_test.py#L406)):*
> ```Python
>         assert user
> 
>         new_email = "user@newemail.com"
> ```

need to assert new email is not the same as the old after this line


<!-- Sent from Reviewable.io -->

2025-01-21 09:54 UTC, SKairinos requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/signals/user.py` line 104 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnx3y9381Yynmb2odR:-OH7H9S17RCOqSMIpoVb:b-485yav) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/signals/user.py#L104)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

let's discuss on quick call
</blockquote></details>

update DD campaign id dict


<!-- Sent from Reviewable.io -->

2025-01-21 17:24 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375)* status: 6 of 12 files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/signals/user.py` line 104 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnx3y9381Yynmb2odR:-OH8t7Fq8a7SMF_wcgut:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/signals/user.py#L104)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

update DD campaign id dict
</blockquote></details>

Done.
___
*[`src/api/signals/user_test.py` line 66 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnxXQx8N_KWxAfg7_K:-OH8t7lG5F8H6szGVGvs:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/aa37bbc35bc4916184296b544574b0280200bcca/src/api/signals/user_test.py#L66)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

let's discuss on quick call
</blockquote></details>

Done.
___
*[`src/api/views/user.py` line 193 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGnyF0E1qJ5KC8KzRYd:-OH8t8M32nu9jkJMdTTp:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/68f490fd078aa2e6f5601b055f9e46fdfa9a71f6/src/api/views/user.py#L193)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

let's discuss on quick call
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-28 14:16 UTC, faucomte97 reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375)* status: 4 of 12 files reviewed, 4 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`src/api/views/user_test.py` line 406 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375#-OGpIaXe0krdUmtHeL5F:-OHhGPCO5rJ29masPlMz:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/885dd92bb4c3575d654fe93c1bdcab0fa691fa46/src/api/views/user_test.py#L406)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

need to assert new email is not the same as the old after this line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-28 17:30 UTC, SKairinos reviewed
> Reviewed 6 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2025-01-28 17:30 UTC, SKairinos approved these changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/375)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)



<!-- Sent from Reviewable.io -->

2025-01-28 17:34 UTC, merged